export type Country = {
  name: string;
  dial: string;
  code: string;
  flag: string;
};

// Popular countries appear first, then alphabetical
export const countries: Country[] = [
  { name: 'United States',        dial: '+1',   code: 'US', flag: '🇺🇸' },
  { name: 'United Kingdom',       dial: '+44',  code: 'GB', flag: '🇬🇧' },
  { name: 'Canada',               dial: '+1',   code: 'CA', flag: '🇨🇦' },
  { name: 'Australia',            dial: '+61',  code: 'AU', flag: '🇦🇺' },
  { name: 'India',                dial: '+91',  code: 'IN', flag: '🇮🇳' },
  { name: 'South Africa',         dial: '+27',  code: 'ZA', flag: '🇿🇦' },
  { name: 'Nigeria',              dial: '+234', code: 'NG', flag: '🇳🇬' },
  { name: 'Zimbabwe',             dial: '+263', code: 'ZW', flag: '🇿🇼' },
  { name: 'Kenya',                dial: '+254', code: 'KE', flag: '🇰🇪' },
  { name: 'Ghana',                dial: '+233', code: 'GH', flag: '🇬🇭' },
  // ── Americas ──────────────────────────────────────────
  { name: 'Argentina',            dial: '+54',  code: 'AR', flag: '🇦🇷' },
  { name: 'Bolivia',              dial: '+591', code: 'BO', flag: '🇧🇴' },
  { name: 'Brazil',               dial: '+55',  code: 'BR', flag: '🇧🇷' },
  { name: 'Chile',                dial: '+56',  code: 'CL', flag: '🇨🇱' },
  { name: 'Colombia',             dial: '+57',  code: 'CO', flag: '🇨🇴' },
  { name: 'Costa Rica',           dial: '+506', code: 'CR', flag: '🇨🇷' },
  { name: 'Cuba',                 dial: '+53',  code: 'CU', flag: '🇨🇺' },
  { name: 'Dominican Republic',   dial: '+1',   code: 'DO', flag: '🇩🇴' },
  { name: 'Ecuador',              dial: '+593', code: 'EC', flag: '🇪🇨' },
  { name: 'Guatemala',            dial: '+502', code: 'GT', flag: '🇬🇹' },
  { name: 'Jamaica',              dial: '+1',   code: 'JM', flag: '🇯🇲' },
  { name: 'Mexico',               dial: '+52',  code: 'MX', flag: '🇲🇽' },
  { name: 'Panama',               dial: '+507', code: 'PA', flag: '🇵🇦' },
  { name: 'Paraguay',             dial: '+595', code: 'PY', flag: '🇵🇾' },
  { name: 'Peru',                 dial: '+51',  code: 'PE', flag: '🇵🇪' },
  { name: 'Uruguay',              dial: '+598', code: 'UY', flag: '🇺🇾' },
  { name: 'Venezuela',            dial: '+58',  code: 'VE', flag: '🇻🇪' },
  // ── Europe ────────────────────────────────────────────
  { name: 'Austria',              dial: '+43',  code: 'AT', flag: '🇦🇹' },
  { name: 'Belgium',              dial: '+32',  code: 'BE', flag: '🇧🇪' },
  { name: 'Croatia',              dial: '+385', code: 'HR', flag: '🇭🇷' },
  { name: 'Czech Republic',       dial: '+420', code: 'CZ', flag: '🇨🇿' },
  { name: 'Denmark',              dial: '+45',  code: 'DK', flag: '🇩🇰' },
  { name: 'Finland',              dial: '+358', code: 'FI', flag: '🇫🇮' },
  { name: 'France',               dial: '+33',  code: 'FR', flag: '🇫🇷' },
  { name: 'Germany',              dial: '+49',  code: 'DE', flag: '🇩🇪' },
  { name: 'Greece',               dial: '+30',  code: 'GR', flag: '🇬🇷' },
  { name: 'Hungary',              dial: '+36',  code: 'HU', flag: '🇭🇺' },
  { name: 'Ireland',              dial: '+353', code: 'IE', flag: '🇮🇪' },
  { name: 'Italy',                dial: '+39',  code: 'IT', flag: '🇮🇹' },
  { name: 'Netherlands',          dial: '+31',  code: 'NL', flag: '🇳🇱' },
  { name: 'Norway',               dial: '+47',  code: 'NO', flag: '🇳🇴' },
  { name: 'Poland',               dial: '+48',  code: 'PL', flag: '🇵🇱' },
  { name: 'Portugal',             dial: '+351', code: 'PT', flag: '🇵🇹' },
  { name: 'Romania',              dial: '+40',  code: 'RO', flag: '🇷🇴' },
  { name: 'Russia',               dial: '+7',   code: 'RU', flag: '🇷🇺' },
  { name: 'Spain',                dial: '+34',  code: 'ES', flag: '🇪🇸' },
  { name: 'Sweden',               dial: '+46',  code: 'SE', flag: '🇸🇪' },
  { name: 'Switzerland',          dial: '+41',  code: 'CH', flag: '🇨🇭' },
  { name: 'Turkey',               dial: '+90',  code: 'TR', flag: '🇹🇷' },
  { name: 'Ukraine',              dial: '+380', code: 'UA', flag: '🇺🇦' },
  // ── Africa ────────────────────────────────────────────
  { name: 'Cameroon',             dial: '+237', code: 'CM', flag: '🇨🇲' },
  { name: 'Egypt',                dial: '+20',  code: 'EG', flag: '🇪🇬' },
  { name: 'Ethiopia',             dial: '+251', code: 'ET', flag: '🇪🇹' },
  { name: 'Ivory Coast',          dial: '+225', code: 'CI', flag: '🇨🇮' },
  { name: 'Morocco',              dial: '+212', code: 'MA', flag: '🇲🇦' },
  { name: 'Mozambique',           dial: '+258', code: 'MZ', flag: '🇲🇿' },
  { name: 'Senegal',              dial: '+221', code: 'SN', flag: '🇸🇳' },
  { name: 'Tanzania',             dial: '+255', code: 'TZ', flag: '🇹🇿' },
  { name: 'Uganda',               dial: '+256', code: 'UG', flag: '🇺🇬' },
  { name: 'Zambia',               dial: '+260', code: 'ZM', flag: '🇿🇲' },
  // ── Middle East ───────────────────────────────────────
  { name: 'Bahrain',              dial: '+973', code: 'BH', flag: '🇧🇭' },
  { name: 'Israel',               dial: '+972', code: 'IL', flag: '🇮🇱' },
  { name: 'Jordan',               dial: '+962', code: 'JO', flag: '🇯🇴' },
  { name: 'Kuwait',               dial: '+965', code: 'KW', flag: '🇰🇼' },
  { name: 'Oman',                 dial: '+968', code: 'OM', flag: '🇴🇲' },
  { name: 'Qatar',                dial: '+974', code: 'QA', flag: '🇶🇦' },
  { name: 'Saudi Arabia',         dial: '+966', code: 'SA', flag: '🇸🇦' },
  { name: 'United Arab Emirates', dial: '+971', code: 'AE', flag: '🇦🇪' },
  // ── Asia ──────────────────────────────────────────────
  { name: 'Bangladesh',           dial: '+880', code: 'BD', flag: '🇧🇩' },
  { name: 'China',                dial: '+86',  code: 'CN', flag: '🇨🇳' },
  { name: 'Hong Kong',            dial: '+852', code: 'HK', flag: '🇭🇰' },
  { name: 'Indonesia',            dial: '+62',  code: 'ID', flag: '🇮🇩' },
  { name: 'Japan',                dial: '+81',  code: 'JP', flag: '🇯🇵' },
  { name: 'Malaysia',             dial: '+60',  code: 'MY', flag: '🇲🇾' },
  { name: 'Nepal',                dial: '+977', code: 'NP', flag: '🇳🇵' },
  { name: 'New Zealand',          dial: '+64',  code: 'NZ', flag: '🇳🇿' },
  { name: 'Pakistan',             dial: '+92',  code: 'PK', flag: '🇵🇰' },
  { name: 'Philippines',          dial: '+63',  code: 'PH', flag: '🇵🇭' },
  { name: 'Singapore',            dial: '+65',  code: 'SG', flag: '🇸🇬' },
  { name: 'South Korea',          dial: '+82',  code: 'KR', flag: '🇰🇷' },
  { name: 'Sri Lanka',            dial: '+94',  code: 'LK', flag: '🇱🇰' },
  { name: 'Taiwan',               dial: '+886', code: 'TW', flag: '🇹🇼' },
  { name: 'Thailand',             dial: '+66',  code: 'TH', flag: '🇹🇭' },
  { name: 'Vietnam',              dial: '+84',  code: 'VN', flag: '🇻🇳' },
];

export const defaultCountry = countries.find(c => c.code === 'ZW')!;
